
'use client';

import React from 'react';
import PropTypes from 'prop-types';


import { Provider } from 'react-redux';
import store from '../../store/store';

// import { Geist, Geist_Mono } from "next/font/google";

import "./style.css";
import "./globals.css";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const  RootLayout = ({ children }) => {

  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          {children}
          </Provider>

        <script src="./js/global.min.js"></script>
        <script src="./js/chart.bundle.min.js"></script>
        {/* <script src="./js/moment.js"></script> */}
        {/* <script src="./js/bootstrap-datetimepicker.min.js"></script> */}
        <script src="./js/bootstrap-select.min.js"></script>
        
       <script src="./js/jquery.peity.min.js"></script>
	
       <script src="./js/apexchart.js"></script>

	    <script src="./js/dashboard-1.js"></script>
	
      <script src="./js/custom.min.js"></script>
      <script src="./js/deznav-init.js"></script>
      {/* <script src="./js/demo.js"></script> */}
      {/* <script src="./js/styleSwitcher.js"></script> */}
      </body>
    </html>
  );

  
}
RootLayout.propTypes = {
  children: PropTypes.node.isRequired,  // Validate that children are passed
};

export default RootLayout;
